import type { MuscleId } from "../../../shared/muscle-taxonomy";

// Display stems omit musculus; English qualifiers describe the app’s training subdivisions.
// Naming reference and grouping boundaries: docs/design/DESIGN.md §6.3.1.
export const muscleBackdropNames = {
  pec_major_upper: "PECTORALIS MAJOR · CLAVICULAR",
  pec_major_mid: "PECTORALIS MAJOR · STERNOCOSTAL",
  pec_major_lower: "PECTORALIS MAJOR · ABDOMINAL",
  deltoid_anterior: "DELTOIDEUS · ANTERIOR",
  deltoid_lateral: "DELTOIDEUS · LATERAL",
  deltoid_posterior: "DELTOIDEUS · POSTERIOR",
  supraspinatus: "SUPRASPINATUS",
  infraspinatus: "INFRASPINATUS",
  teres_minor: "TERES MINOR",
  subscapularis: "SUBSCAPULARIS",
  serratus_anterior: "SERRATUS ANTERIOR",
  trapezius_upper: "TRAPEZIUS · UPPER",
  trapezius_middle: "TRAPEZIUS · MIDDLE",
  trapezius_lower: "TRAPEZIUS · LOWER",
  rhomboid_major: "RHOMBOIDEUS MAJOR",
  levator_scapulae: "LEVATOR SCAPULAE",
  teres_major: "TERES MAJOR",
  latissimus_dorsi: "LATISSIMUS DORSI",
  erector_spinae_upper: "ERECTOR SPINAE · UPPER",
  erector_spinae_lower: "ERECTOR SPINAE · LOWER",
  biceps_long_head: "BICEPS BRACHII · LONG HEAD",
  biceps_short_head: "BICEPS BRACHII · SHORT HEAD",
  brachialis: "BRACHIALIS",
  triceps_long_head: "TRICEPS BRACHII · LONG HEAD",
  triceps_lateral_head: "TRICEPS BRACHII · LATERAL HEAD",
  triceps_medial_head: "TRICEPS BRACHII · MEDIAL HEAD",
  forearm_flexors: "FOREARM FLEXORS",
  forearm_extensors: "FOREARM EXTENSORS",
  brachioradialis: "BRACHIORADIALIS",
  pronator_teres: "PRONATOR TERES",
  supinator: "SUPINATOR",
  rectus_abdominis_upper: "RECTUS ABDOMINIS · UPPER",
  rectus_abdominis_lower: "RECTUS ABDOMINIS · LOWER",
  external_oblique: "OBLIQUUS EXTERNUS ABDOMINIS",
  internal_oblique: "OBLIQUUS INTERNUS ABDOMINIS",
  transversus_abdominis: "TRANSVERSUS ABDOMINIS",
  quadratus_lumborum: "QUADRATUS LUMBORUM",
  diaphragm: "DIAPHRAGMA",
  gluteus_maximus: "GLUTEUS MAXIMUS",
  gluteus_medius: "GLUTEUS MEDIUS",
  gluteus_minimus: "GLUTEUS MINIMUS",
  tensor_fasciae_latae: "TENSOR FASCIAE LATAE",
  iliopsoas: "ILIOPSOAS",
  sartorius: "SARTORIUS",
  rectus_femoris: "RECTUS FEMORIS",
  vastus_lateralis: "VASTUS LATERALIS",
  vastus_medialis: "VASTUS MEDIALIS",
  vastus_intermedius: "VASTUS INTERMEDIUS",
  adductor_longus: "ADDUCTOR LONGUS",
  adductor_magnus: "ADDUCTOR MAGNUS",
  adductor_brevis: "ADDUCTOR BREVIS",
  gracilis: "GRACILIS",
  pectineus: "PECTINEUS",
  biceps_femoris_long_head: "BICEPS FEMORIS · LONG HEAD",
  biceps_femoris_short_head: "BICEPS FEMORIS · SHORT HEAD",
  semitendinosus: "SEMITENDINOSUS",
  semimembranosus: "SEMIMEMBRANOSUS",
  gastrocnemius_medial: "GASTROCNEMIUS · MEDIAL HEAD",
  gastrocnemius_lateral: "GASTROCNEMIUS · LATERAL HEAD",
  soleus: "SOLEUS",
  tibialis_anterior: "TIBIALIS ANTERIOR",
  extensor_digitorum_longus: "EXTENSOR DIGITORUM LONGUS",
  fibularis_longus: "FIBULARIS LONGUS",
  fibularis_brevis: "FIBULARIS BREVIS",
  tibialis_posterior: "TIBIALIS POSTERIOR",
  popliteus: "POPLITEUS",
  sternocleidomastoid: "STERNOCLEIDOMASTOIDEUS"
} satisfies Record<MuscleId, string>;
