// Display metadata only. Muscle relationships belong exclusively to muscle_map.yaml.
export const exerciseLabels: Readonly<Record<string, string>> = {
  pull_up: "引体向上",
  lat_pulldown: "高位下拉",
  romanian_deadlift: "罗马尼亚硬拉",
  split_squat: "分腿蹲",
  plank: "平板支撑",
  horizontal_press: "水平推胸",
  incline_press: "上斜推胸",
  horizontal_row: "水平划船",
  assisted_pull_up: "辅助引体向上",
  deadlift: "硬拉",
  single_leg_deadlift: "单腿硬拉",
  squat: "深蹲",
  wide_squat: "宽距深蹲",
  step_up: "登阶",
  overhead_press: "过顶推举",
  lateral_raise: "侧平举",
  upright_row: "直立划船",
  hip_abduction: "髋外展",
  hip_adduction: "髋内收",
  leg_curl: "腿弯举",
  leg_press: "蹬腿",
  rear_delt_pull: "肩后束拉",
  dip: "双杠臂屈伸",
  triceps_pressdown: "肱三头下压",
  hammer_curl: "锤式弯举",
  biceps_curl: "肱二头弯举",
  leg_extension: "腿屈伸",
  leg_raise: "举腿 / 卷腹",
  side_plank: "侧平板支撑",
  cross_body_crunch: "交叉卷腹",
  squat_press: "深蹲推举"
};
