export const muscleIds = [
  "pec_major_upper",
  "pec_major_mid",
  "pec_major_lower",
  "deltoid_anterior",
  "deltoid_lateral",
  "deltoid_posterior",
  "supraspinatus",
  "infraspinatus",
  "teres_minor",
  "subscapularis",
  "serratus_anterior",
  "trapezius_upper",
  "trapezius_middle",
  "trapezius_lower",
  "rhomboid_major",
  "levator_scapulae",
  "teres_major",
  "latissimus_dorsi",
  "erector_spinae_upper",
  "erector_spinae_lower",
  "biceps_long_head",
  "biceps_short_head",
  "brachialis",
  "triceps_long_head",
  "triceps_lateral_head",
  "triceps_medial_head",
  "forearm_flexors",
  "forearm_extensors",
  "brachioradialis",
  "pronator_teres",
  "supinator",
  "rectus_abdominis_upper",
  "rectus_abdominis_lower",
  "external_oblique",
  "internal_oblique",
  "transversus_abdominis",
  "quadratus_lumborum",
  "diaphragm",
  "gluteus_maximus",
  "gluteus_medius",
  "gluteus_minimus",
  "tensor_fasciae_latae",
  "iliopsoas",
  "sartorius",
  "rectus_femoris",
  "vastus_lateralis",
  "vastus_medialis",
  "vastus_intermedius",
  "adductor_longus",
  "adductor_magnus",
  "adductor_brevis",
  "gracilis",
  "pectineus",
  "biceps_femoris_long_head",
  "biceps_femoris_short_head",
  "semitendinosus",
  "semimembranosus",
  "gastrocnemius_medial",
  "gastrocnemius_lateral",
  "soleus",
  "tibialis_anterior",
  "extensor_digitorum_longus",
  "fibularis_longus",
  "fibularis_brevis",
  "tibialis_posterior",
  "popliteus",
  "sternocleidomastoid"
] as const;

export type MuscleId = (typeof muscleIds)[number];

export const muscleLabels = {
  pec_major_upper: "胸大肌上部 / 锁骨部",
  pec_major_mid: "胸大肌中部 / 胸肋部",
  pec_major_lower: "胸大肌下部 / 腹部纤维",
  deltoid_anterior: "三角肌前束",
  deltoid_lateral: "三角肌中束",
  deltoid_posterior: "三角肌后束",
  supraspinatus: "冈上肌",
  infraspinatus: "冈下肌",
  teres_minor: "小圆肌",
  subscapularis: "肩胛下肌",
  serratus_anterior: "前锯肌",
  trapezius_upper: "上斜方肌",
  trapezius_middle: "中斜方肌",
  trapezius_lower: "下斜方肌",
  rhomboid_major: "大菱形肌",
  levator_scapulae: "肩胛提肌",
  teres_major: "大圆肌",
  latissimus_dorsi: "背阔肌",
  erector_spinae_upper: "上段竖脊肌",
  erector_spinae_lower: "下段竖脊肌",
  biceps_long_head: "肱二头肌长头",
  biceps_short_head: "肱二头肌短头",
  brachialis: "肱肌",
  triceps_long_head: "肱三头肌长头",
  triceps_lateral_head: "肱三头肌外侧头",
  triceps_medial_head: "肱三头肌内侧头",
  forearm_flexors: "前臂屈肌群",
  forearm_extensors: "前臂伸肌群",
  brachioradialis: "肱桡肌",
  pronator_teres: "旋前圆肌",
  supinator: "旋后肌",
  rectus_abdominis_upper: "上腹直肌",
  rectus_abdominis_lower: "下腹直肌",
  external_oblique: "腹外斜肌",
  internal_oblique: "腹内斜肌",
  transversus_abdominis: "腹横肌",
  quadratus_lumborum: "腰方肌",
  diaphragm: "膈肌",
  gluteus_maximus: "臀大肌",
  gluteus_medius: "臀中肌",
  gluteus_minimus: "臀小肌",
  tensor_fasciae_latae: "阔筋膜张肌",
  iliopsoas: "髂腰肌",
  sartorius: "缝匠肌",
  rectus_femoris: "股直肌",
  vastus_lateralis: "股外侧肌",
  vastus_medialis: "股内侧肌",
  vastus_intermedius: "股中间肌",
  adductor_longus: "长收肌",
  adductor_magnus: "大收肌",
  adductor_brevis: "短收肌",
  gracilis: "股薄肌",
  pectineus: "耻骨肌",
  biceps_femoris_long_head: "股二头肌长头",
  biceps_femoris_short_head: "股二头肌短头",
  semitendinosus: "半腱肌",
  semimembranosus: "半膜肌",
  gastrocnemius_medial: "腓肠肌内侧头",
  gastrocnemius_lateral: "腓肠肌外侧头",
  soleus: "比目鱼肌",
  tibialis_anterior: "胫骨前肌",
  extensor_digitorum_longus: "趾长伸肌",
  fibularis_longus: "腓骨长肌",
  fibularis_brevis: "腓骨短肌",
  tibialis_posterior: "胫骨后肌",
  popliteus: "腘肌",
  sternocleidomastoid: "胸锁乳突肌"
} satisfies Record<MuscleId, string>;
