import { format, resolveConfig } from "prettier";
import { readFile, readdir, writeFile } from "node:fs/promises";

const tokens = JSON.parse(
  await readFile(new URL("../src/design/tokens.json", import.meta.url), "utf8")
);
const graphite = JSON.parse(
  await readFile(new URL("../src/design/graphite.json", import.meta.url), "utf8")
);
const unknownOverrides = Object.keys(graphite).filter((name) => !Object.hasOwn(tokens, name));
if (unknownOverrides.length > 0) {
  throw new Error(`Graphite 覆盖了未定义的 Neon token：${unknownOverrides.join("、")}`);
}

const block = (selector, values) =>
  `${selector} {\n${Object.entries(values)
    .map(([name, value]) => `  --${name}: ${value};`)
    .join("\n")}\n}\n`;
const source =
  "/* Generated by npm run design:tokens. Edit tokens.json / graphite.json. */\n" +
  block(':root, [data-theme="neon"]', tokens) +
  block('[data-theme="graphite"]', { ...tokens, ...graphite }) +
  block(':root[data-glow="off"]', { "glow-accent": "none", "glow-selection": "none" });
const target = new URL("../src/design/tokens.css", import.meta.url);
const output = await format(source, { ...(await resolveConfig(target)), parser: "css" });
if (process.argv.includes("--check")) {
  if ((await readFile(target, "utf8")) !== output) {
    throw new Error("设计 token 已漂移，请运行 npm run design:tokens");
  }
  await checkThemeStyles();
  console.log("CSS / 3D 设计 token 一致，主题覆盖与主站颜色边界检查通过");
} else {
  await writeFile(target, output);
}

async function checkThemeStyles() {
  const dashboardFiles = await readdir(new URL("../src/features/dashboard/", import.meta.url));
  const files = [
    "src/styles.css",
    "src/components/icon-button.css",
    "src/components/glass-card.css",
    "src/features/body-3d/body-viewer.css",
    "src/features/chat/session-history.css",
    ...dashboardFiles
      .filter((name) => name.endsWith(".css"))
      .map((name) => `src/features/dashboard/${name}`),
    "src/features/muscles/muscle-picker.css",
    "src/features/settings/appearance/appearance.css",
    "src/features/settings/settings.css"
  ];
  const violations = [];
  for (const file of files) {
    const css = await readFile(new URL(`../${file}`, import.meta.url), "utf8");
    // Preserve line offsets while excluding documentation comments.
    const declarations = css.replace(/\/\*[\s\S]*?\*\//g, (comment) =>
      comment.replace(/[^\n]/g, " ")
    );
    const directColor =
      /#(?:[\da-f]{8}|[\da-f]{6}|[\da-f]{4}|[\da-f]{3})(?![\w-])|\b(?:rgba?|hsla?)\s*\(/gi;
    for (const match of declarations.matchAll(directColor)) {
      const line = declarations.slice(0, match.index).split("\n").length;
      violations.push(`${file}:${line} ${match[0]}`);
    }
  }
  if (violations.length > 0) {
    throw new Error(`主站样式禁止直接颜色值；请复用 src/design token：\n${violations.join("\n")}`);
  }
}
